#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 09, 2020 11:55:17 AM +06  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
from console_out.console_out_gui_file import printCon
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    import MMCL_monitoring_9_May_2020
    global Ping_title,ip_address
    Ping_title = []
    ip_address = []
    ip_list = MMCL_monitoring_9_May_2020.extraInfo.get_ip_list()
    for i in ip_list:
        a = tk.StringVar()
        a.set(i[0])
        b = tk.StringVar()
        b.set(i[1])
        Ping_title.append(a)
        ip_address.append(b)
    print(f"Ping_title = {Ping_title}")
    printCon(f"Ping_title = {Ping_title}")
    print(f"ip_address = {ip_address}")
    printCon(f"ip_address = {ip_address}")
    global che59
    che59 = tk.StringVar()
    global ip_serial
    ip_serial = tk.StringVar()
    ip_serial.set('No.')

def set_entry_values():
    pass

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global ping_setting_window_control
    ping_setting_window_control = False
    print(f"window destroyed...value = .{ping_setting_window_control}")
    global top_level
    top_level.destroy()
    top_level = None



# if __name__ == '__main__':
#     import ping_set
#     ping_set.vp_start_gui()




