#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 12, 2020 02:36:46 PM +06  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

try:
    import formula__support
except:
    import formula_gui.formula__support as formula__support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    formula__support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    formula__support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("679x425+354+133")
        top.title("Telecom Formulas")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.015, rely=0.024, relheight=0.953
                , relwidth=0.979)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=665)

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.015, rely=0.025, relheight=0.185, relwidth=0.97)

        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(width=645)

        self.Label1 = tk.Label(self.Frame2)
        self.Label1.place(relx=0.202, rely=0.133, height=50, width=434)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 13")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(justify='left')
        self.Label1.configure(text='''CCR = Call Completion Rate
CCR  = (Connect Number / Attempt Number)*100%''')
        self.Label1.configure(width=434)

        # self.Label1_3 = tk.Label(self.Frame2)
        # # self.Label1_3.place(relx=0.186, rely=0.533, height=21, width=474)
        # self.Label1_3.configure(activebackground="#f9f9f9")
        # self.Label1_3.configure(activeforeground="black")
        # self.Label1_3.configure(background="#d9d9d9")
        # self.Label1_3.configure(disabledforeground="#a3a3a3")
        # self.Label1_3.configure(font="-family {Segoe UI} -size 13")
        # self.Label1_3.configure(foreground="#000000")
        # self.Label1_3.configure(highlightbackground="#d9d9d9")
        # self.Label1_3.configure(highlightcolor="black")
        # self.Label1_3.configure(text='''CCR  = (Connect Number / Attempt Number)*100%''')
        # self.Label1_3.configure(width=474)

        self.Frame2_5 = tk.Frame(self.Frame1)
        self.Frame2_5.place(relx=0.015, rely=0.222, relheight=0.185, relwidth=0.97)
        # self.Frame2_6.place(relx=0.015, rely=0.42, relheight=0.185, relwidth=0.97)
        self.Frame2_5.configure(relief='groove')
        self.Frame2_5.configure(borderwidth="2")
        self.Frame2_5.configure(relief="groove")
        self.Frame2_5.configure(background="#d9d9d9")
        self.Frame2_5.configure(highlightbackground="#d9d9d9")
        self.Frame2_5.configure(highlightcolor="black")
        self.Frame2_5.configure(width=645)

        self.Label1_6 = tk.Label(self.Frame2_5)
        self.Label1_6.place(relx=0.202, rely=0.133, height=50, width=414)
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#d9d9d9")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(font="-family {Segoe UI} -size 13")
        self.Label1_6.configure(foreground="#000000")
        self.Label1_6.configure(highlightbackground="#d9d9d9")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(justify='left')
        self.Label1_6.configure(text='''ASR = Answer Seizure Ratio
ASR = (Answer Number / Attempt Number)*100%''')
        self.Label1_6.configure(width=434)

        # self.Label1_4 = tk.Label(self.Frame2_5)
        # # self.Label1_4.place(relx=0.202, rely=0.533, height=21, width=404)
        # self.Label1_4.configure(activebackground="#f9f9f9")
        # self.Label1_4.configure(activeforeground="black")
        # self.Label1_4.configure(background="#d9d9d9")
        # self.Label1_4.configure(disabledforeground="#a3a3a3")
        # self.Label1_4.configure(font="-family {Segoe UI} -size 13")
        # self.Label1_4.configure(foreground="#000000")
        # self.Label1_4.configure(highlightbackground="#d9d9d9")
        # self.Label1_7.configure(justify='left')
        # self.Label1_4.configure(text='''ASR = (Answer Number / Attempt Number)*100%''')
        # self.Label1_4.configure(width=404)

        self.Frame2_6 = tk.Frame(self.Frame1)
        self.Frame2_6.place(relx=0.015, rely=0.42, relheight=0.185, relwidth=0.97)
        self.Frame2_6.configure(relief='groove')
        self.Frame2_6.configure(borderwidth="2")
        self.Frame2_6.configure(relief="groove")
        self.Frame2_6.configure(background="#d9d9d9")
        self.Frame2_6.configure(highlightbackground="#d9d9d9")
        self.Frame2_6.configure(highlightcolor="black")
        self.Frame2_6.configure(width=645)

        self.Label1_7 = tk.Label(self.Frame2_6)
        self.Label1_7.place(relx=0.202, rely=0.133, height=50, width=414)
        # self.Label1_6.place(relx=0.202, rely=0.133, height=50, width=414)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font="-family {Segoe UI} -size 13")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(justify='left')
        self.Label1_7.configure(text='''ACD = Average Call Duration
ACD  = (Answer Time / Answer Number)/60''')
        self.Label1_7.configure(width=434)


        # self.Label1_4 = tk.Label(self.Frame2_6)
        # # self.Label1_4.place(relx=0.171, rely=0.533, height=21, width=474)
        # self.Label1_4.configure(activebackground="#f9f9f9")
        # self.Label1_4.configure(activeforeground="black")
        # self.Label1_4.configure(background="#d9d9d9")
        # self.Label1_4.configure(disabledforeground="#a3a3a3")
        # self.Label1_4.configure(font="-family {Segoe UI} -size 13")
        # self.Label1_4.configure(foreground="#000000")
        # self.Label1_4.configure(highlightbackground="#d9d9d9")
        # self.Label1_4.configure(highlightcolor="black")
        # self.Label1_4.configure(justify='left')
        # self.Label1_4.configure(text='''ACD  = (Answer Time / Answer Number)/60''')

        self.Frame3 = tk.Frame(self.Frame1)
        self.Frame3.place(relx=0.015, rely=0.617, relheight=0.358, relwidth=0.97)

        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d9d9d9")
        self.Frame3.configure(width=645)

        self.fra43_fra62_lab63 = tk.Label(self.Frame3)
        self.fra43_fra62_lab63.place(relx=0.202, rely=0.069, height=121
                , width=384)
        self.fra43_fra62_lab63.configure(activebackground="#f9f9f9")
        self.fra43_fra62_lab63.configure(activeforeground="black")
        self.fra43_fra62_lab63.configure(background="#d9d9d9")
        self.fra43_fra62_lab63.configure(disabledforeground="#a3a3a3")
        self.fra43_fra62_lab63.configure(font="-family {Segoe UI} -size 13")
        self.fra43_fra62_lab63.configure(foreground="#000000")
        self.fra43_fra62_lab63.configure(highlightbackground="#d9d9d9")
        self.fra43_fra62_lab63.configure(highlightcolor="black")
        self.fra43_fra62_lab63.configure(justify='left')
        self.fra43_fra62_lab63.configure(text='''KPI = Key Performance Indicator
ICX = Interconnection Exchange
IGW = International Gateway
IIG = International Internet Gageway
IOF = IGW Operations Forum''')
        self.fra43_fra62_lab63.configure(width=434)

if __name__ == '__main__':
    vp_start_gui()





